### ISSUE TITLE
Feature Request - Input No Resi dan Waybill 

### ISSUE THREAD

**Issue by aryoprakarsa** [sofyansitorus/Woongkir#10]
Mas Sofyan,

Alangkah bagusnya apabila pada order bisa di input no resi dan pada saat di halaman order -> view details bisa untuk waybill statusnya pengiriman

**Comment by erikdemarco** [comment]
uda ada plugin ini dr developer woocommrce. jadi saya rasa fitur2 yang uda ada ga usah diinclude agar plugin ga jadi terlalu besar malah akan membuat wordpress jadi lambat
