### ISSUE TITLE
Tolong include filter original dari woocommerce.

### ISSUE THREAD

**Issue by erikdemarco** [sofyansitorus/Woongkir#11]
Hi, Tolong masukkan filter original dr woocommerce shipping seperti:
woocommerce_package_rates
woocommerce_shipping_packages

yang ada di sini:
https://github.com/woocommerce/woocommerce/blob/e989b7cb037e0f45a238aa8d47cc95a9915f24fe/includes/class-wc-shipping.php

karena sangat membantu untuk migrasi dr plugin lain. jadi ga perlu ganti hook lagi dr settingan lama

**Comment by sofyansitorus** [comment]
Plugin ini menggunakan function built-in dari woocommerce WC_Shipping_Method::add_rate. And bisa mengunakan filter `woocommerce_shipping_method_add_rate` jika ingin memodifikasi hasil ongkir yang dikalkulasikan oleh Woongkir. 

Dan saya tidak menemukan relevansi antara plugin ini dengan plugin lain. Jika anda baru saja mengintall plugin Woongkir, tentu saja anda harus melakukan setting.
