### ISSUE TITLE
tolong buat filter sendiri untuk 'show_debug'

### ISSUE THREAD

**Issue by erikdemarco** [sofyansitorus/Woongkir#12]
Halo, saya mengubah woocommerce_shipping_debug_mode menjadi 'yes' karena untuk memforce woocommerce calculate shipping setiap request. tapi malah debug dari woongkir ikut ke show juga. Harusnya woongkir punya filter sendiri untuk woocommerce_shipping_debug_mode jadi ga menganggu plugin lain yang mau memforce woocommerce untuk calculate everytime dengan hook ini.

**Comment by sofyansitorus** [comment]
Debug Woongkir hanya akan ditampilkan ke admin user yang sedang login. Dan tidak akan mengganggu sama sekali ke user biasa. Woocommerce debug di tutujukan untuk trouble shooting, bukan mem-force calculate shipping setinp request. Jadi isu ini sangat tidak relevan.
