### ISSUE TITLE
error from api rajaongkir

### ISSUE THREAD

**Issue by moca-stgm** [sofyansitorus/Woongkir#13]
error saat melakukan penyetingan zona pengiriman

Error from RajaOngkir.com: cURL error 28: Connection timed out after 10000 milliseconds
![IMG_20210202_121255](https://user-images.githubusercontent.com/75295452/106555366-01633500-6550-11eb-9bee-3d60b6824e62.png)

**Comment by sofyansitorus** [comment]
Saya sarankan anda agar mengganti hosting anda agar lebih reliable. Silakan cek link berikut untuk info lebih lanjut:

https://wordpress.org/support/topic/curl-error-28-connection-timed-out-after-10001-milliseconds/
