### ISSUE TITLE
BUG class-raja-ongkir.php

### ISSUE THREAD

**Issue by erikdemarco** [sofyansitorus/Woongkir#20]
https://github.com/sofyansitorus/Woongkir/blob/80395e944e047423e8f5ef2d31f70a7c7106e312/includes/class-raja-ongkir.php

when doing validate_account() with 'starter' account type. its not working.
The bug is in line 333

**Comment by sofyansitorus** [comment]
@erikdemarco Thanks for the report. Please submit pull request if you have it. I will appreciate it.
