### ISSUE TITLE
Mengubah nama kurir

### ISSUE THREAD

**Issue by arnolduspt** [sofyansitorus/Woongkir#22]
Halo mas, saya ingin mengubah nama kurir menjadi misalnya FEDEX menjadi FAST EXPRESS
.
Sebenarnya saya sudah sempat membaca ini https://wordpress.org/support/topic/asuransi-ganti-nama-kurir/
Namun saya kurang mengerti penerapannya
Bisa dibantu mas, untuk penerapan cara menggunakan filter hook untuk mengubah label woongkir?
Terimakasihhh

**Comment by sofyansitorus** [comment]
Berikut contoh sederhana dari penerapan filter `woongkir_shipping_rate_label`:

```
function my_woongkir_shipping_rate_label( $label ) {
	if ( 'FEDEX' === $label ) {
		return 'FAST EXPRESS';
	}

	return $label;
}

add_filter( 'woongkir_shipping_rate_label', 'my_woongkir_shipping_rate_label' );
```
