### ISSUE TITLE
Convert ongkos kirim ke mata uang lain dengan kode

### ISSUE THREAD

**Issue by arnolduspt** [sofyansitorus/Woongkir#26]
Hai mas. Saya penggemar berat plugin ini, terlebih karena saya pengguna woofunnel yg entah kenapa hanya woongkir yang support digunakan secara bersamaan.
.
Jadi begini mas, ongkos kirim yang ditampilkan oleh plugin ini kan IDR ya, bisakah saya membuat kode untuk "get shipping/price id"nya agar bisa saya kalkulasi melalui kode yang nantinya disisipkan pada theme-funcfion.
.
Yang ingin saya capai yaitu
(1) Membuat kode agar price yang tampil otomatos di tambah dengan nominal tertentu, misalnya 10.0000
(2) Membuat kode agar price dapat di convert ke USD tanpa plugin multi currency.
.
Adakah hook atau apapun yang mengarah pada hasil ongkos kirim yang ditampilkan?
Salam, termakasih.

**Comment by sofyansitorus** [comment]
@arnolduspt Anda bisa menggunakan filter `woocommerce_shipping_method_add_rate_args`. Berikut contoh kode untuk mengkonversi ongkir ke mata uang sesuai seting WooCommerce:

```
add_filter( 'woocommerce_shipping_method_add_rate_args',  function( $rate ) {
    if ( isset( $rate['id'] ) && 0 === strpos( $rate['id'], 'woongkir:' ) ) {
        $exchange_rates = array(
            'USD' => 15000,
            'GBP' => 16000,
        );

        $selected_currency = get_woocommerce_currency();

        if ( isset( $exchange_rates[ $selected_currency ] ) ) {
            $rate['cost'] = ( 1 / $exchange_rates[ $selected_currency ] ) * $rate['cost'];
        }
    }

    return $rate;
} );
```

**Comment by sofyansitorus** [comment]
Berikut contoh kode untuk mengkonversi ongkir ke mata uang sesuai seting WooCommerce and extra cost 10000:

```
add_filter( 'woocommerce_shipping_method_add_rate_args',  function( $rate ) {
    if ( isset( $rate['id'] ) && 0 === strpos( $rate['id'], 'woongkir:' ) ) {
        // Extra cost.
        $rate['cost'] += 10000;

        // Convert to foreign currency.
        $exchange_rates = array(
            'USD' => 15000,
            'GBP' => 16000,
        );

        $selected_currency = get_woocommerce_currency();

        if ( isset( $exchange_rates[ $selected_currency ] ) ) {
            $rate['cost'] = ( 1 / $exchange_rates[ $selected_currency ] ) * $rate['cost'];
        }
    }

    return $rate;
} );
```

**Comment by arnolduspt** [comment]
Maaf mau nanya lagi mas. Semisal yang kita berikan extra cost itu hanya untuk shipping method tertentu apakah memungkinkan mas? #Terimakasih

**Comment by BarCAD** [comment]
> @arnolduspt Anda bisa menggunakan filter `woocommerce_shipping_method_add_rate_args`. Berikut contoh kode untuk mengkonversi ongkir ke mata uang sesuai seting WooCommerce:
> 
> ```
> add_filter( 'woocommerce_shipping_method_add_rate_args',  function( $rate ) {
>     if ( isset( $rate['id'] ) && 0 === strpos( $rate['id'], 'woongkir:' ) ) {
>         $exchange_rates = array(
>             'USD' => 15000,
>             'GBP' => 16000,
>         );
> 
>         $selected_currency = get_woocommerce_currency();
> 
>         if ( isset( $exchange_rates[ $selected_currency ] ) ) {
>             $rate['cost'] = ( 1 / $exchange_rates[ $selected_currency ] ) * $rate['cost'];
>         }
>     }
> 
>     return $rate;
> } );
> ```

pasangnya dimana bang.. maklum newbi hehe
