### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by BarCAD** [sofyansitorus/Woongkir#33]
pakai API rajaongkir pro, seting woocommerce USD, tapi harga nasih rupiah yang muncul. wordpress sudah V6,4,4... adakah Solusinya Bang.. Mentok nih hehe

**Comment by sofyansitorus** [comment]
@BarCAD Anda bisa menambahkan kode berikut kedalaam file functions.php yand terdapat pada directory theme yang anda gunakan:

```PHP
add_filter( 'woocommerce_shipping_method_add_rate_args',  function( $rate ) {
    if ( isset( $rate['id'] ) && 0 === strpos( $rate['id'], 'woongkir:' ) ) {
        $exchange_rates = array(
            'USD' => 15000,
            'GBP' => 16000,
        );

        $selected_currency = get_woocommerce_currency();

        if ( isset( $exchange_rates[ $selected_currency ] ) ) {
            $rate['cost'] = ( 1 / $exchange_rates[ $selected_currency ] ) * $rate['cost'];
        }
    }

    return $rate;
} );
```

Kode tersebut akan mengkonversi cost dari Woongkir ke USD denga rate 15000/USD atau GBP dengan rate 16000/GBP. Silakan disesuaikan rate konversi nya sesuai kebutuhan.

**Comment by BarCAD** [comment]
Sudah berhasil bang. Tapi currency manual ya.. gak update BI?? ...
Terimakasih bang

Pada Min, 19 Mei 2024 19.59, Sofyan Sitorus ***@***.***>
menulis:

**Comment by sofyansitorus** [comment]
> gak update BI??

Ya saya bisa buatin kalau mau pake rate BI, tapi mahal. Sebaiknya anda rajin2 saja edit manual ratenya setiap ada perubahan rate dari BI. Anggap saja latihan ngoding. Hehe..

**Comment by BarCAD** [comment]
Terimakasih bang... Untuk semuanya...sangat bermanfaat

Pada Sen, 20 Mei 2024 11.49, Sofyan Sitorus ***@***.***>
menulis:
