### ISSUE TITLE
Enable compression for the following resources to reduce their transfer size by 1.0MiB (91% reduction).

### ISSUE THREAD

**Issue by vallerydelexy** [sofyansitorus/Woongkir#34]
Compressing .../wp-content/plugins/woongkir/data/**subdistrict.json**?t=1571132909 could save 993.8KiB **(92% reduction)**.
Compressing .../wp-content/plugins/woongkir/data/**city.json**?t=1571132909 could save 55.4KiB **(87% reduction)**.
Compressing .../wp-content/plugins/woongkir/data/**country.json**?t=1571132909 could save 11.9KiB **(81% reduction)**.
Compressing .../wp-content/plugins/woongkir/data/**province.json**?t=1571132909 could save 1.5KiB **(76% reduction)**.

**Comment by sofyansitorus** [comment]
Thanks for the feedback. Actually the JSON data has been optimised by removing all whitespace and comments. The other compression method could be done from the server side  which this plugin has nothing to do with it.
