### ISSUE TITLE
Shipping Cost doesn't show on checkout

### ISSUE THREAD

**Issue by anastiakristiana** [sofyansitorus/Woongkir#5]
Hello,
I'm using your Woongkir plugin, but the shipping cost doesn't show on checkout page.
It says : There are no shipping methods available. Please ensure that your address has been entered correctly, or contact us if you need any help.

Berikut tampilan di halaman checkout: 
![rjongkir1](https://user-images.githubusercontent.com/37280126/44827543-be455f00-ac3d-11e8-91f1-119694cbaf1e.PNG)

Berikut tampilan setting Woongkir:
![rjongkir2](https://user-images.githubusercontent.com/37280126/44827592-f2b91b00-ac3d-11e8-821d-2cc5cd6767fd.PNG)
![rjongkir3](https://user-images.githubusercontent.com/37280126/44827598-f5b40b80-ac3d-11e8-9cca-b0ce7ea0d0e0.PNG)

Note:
I already used the API Key from RajaOngkir account, I just remove it from the captured image.

**Comment by sofyansitorus** [comment]
Hi @anastiakristiana ,

Could you please try try to switch the WooCommerce Shipping Debug Mode setting to “On”. Then open your cart/checkout page. You will see the error printed if there was.

[Click here](https://fast.wistia.net/embed/iframe/9c9008dxnr) for how to switch WooCommerce Shipping Debug Mode.

**Comment by sofyansitorus** [comment]
As I haven't heard from you since my last reply, thus I close this issue.
