### ISSUE TITLE
City not select-able on checkout with new account

### ISSUE THREAD

**Issue by randhipp** [sofyansitorus/Woongkir#6]
hello, i've had some trouble, 

![image](https://user-images.githubusercontent.com/25372728/83316434-df424600-a24f-11ea-8050-1722dfdf9d1e.png)

city not select-able if using a new not registered user.

But it is working if using registered customer and billing address already configured in my-account

![image](https://user-images.githubusercontent.com/25372728/83316574-c4bc9c80-a250-11ea-9fbe-8b7bd046e755.png)

![image](https://user-images.githubusercontent.com/25372728/83316486-36481b00-a250-11ea-81dd-96dd9ac10e4e.png)

WP:  5.4.1	
WC: 4.1.1
Theme:  Flatsome 3.11.3 

is there any way to fix this, i'll try to fix it myself just pass me a hint please.

thanks.

**Comment by sofyansitorus** [comment]
I believe this something caused by the Flatsome theme which probably modify the WooCommerce address fields structure. This plugin rely on address fields ID attribute. Make sure it was exist and valid.
