### ISSUE TITLE
Untuk ongkir JNE tidak muncul

### ISSUE THREAD

**Issue by indotronic** [sofyansitorus/Woongkir#7]
nyoba pertama kali install,
JNE tidk muncul
tiki dan pos indonesia muncul

**Comment by aditvdev** [comment]
Mulai 7 agustus kemaren raja ongkir sudah tidak mendukung JNE.

**Comment by aadiityaak** [comment]
Tp memang raja ongkir mulai 7 agustus kemaren sudah tidak mendukung ekspedisi JNE.

**Comment by benyaminl** [comment]
Ongkir masih di support oleh JNE. Yang hilang hanya cek resi. bukan cek ongkir.
