### ISSUE TITLE
DKI Jakarta Tidak terdeteksi.

### ISSUE THREAD

**Issue by Blek182** [sofyansitorus/Woongkir#9]
Tolong di check, sepertinya BUG di bagian Provinsi, Hanya dibagian ketika akan memasukan alamat daerah DKI Jakarta. Tidak terdeteksi.

"There are no shipping methods available. Please ensure that your address has been entered correctly, or contact us if you need any help."

Pasti selalu begitu ketika ganti alamat ke daerah DKI Jakarta.

Mohon ditinjau, terimakasih.

NB: Oh iya, alamat Origin yang Saya masukan di Jakarta. (Mungkin Membantu).

**Comment by sofyansitorus** [comment]
Halo @Blek182, apa saja jenis kurir yang anda aktifkan?

**Comment by Blek182** [comment]
Oh iya, Saya hanya mengaktifkan JNE saja.

Terimakasih atas responnya pak @sofyansitorus

**Comment by sofyansitorus** [comment]
Oke, setau saya JNE unutk pengirim dalam kota yang sama itu hanya bisa dengan layayanan CTC. APakah JNE CTC sudah diaktifkan?

**Comment by Blek182** [comment]
Owalah, betul sekali. Ternyata itu penyebabnya. Iya saya belum diaktifkan JNE CTC nya. Sekarang sudah berjalan dengan baik.
Terimakasih pak, plugin nya bagus banget.

Sukses & Sehat Selalu.

**Comment by sofyansitorus** [comment]
Thanks om, jika berkenan sudi kiranya untuk submit rating & review di https://wordpress.org/plugins/woongkir/#reviews

**Comment by Blek182** [comment]
Sudah saya Rating & Review, TOP markotop Plugin nya :D

**Comment by sofyansitorus** [comment]
Terima kasih atas rating dan review nya ya om
